// 국가별 평균 IQ "추정치" — 여러 공개 국제 연구에서 널리 인용되는 값.
// ⚠️ 이 수치는 출처·방법론에 따라 크게 달라지며, 교육 접근성·영양·검사 친숙도·
// 플린 효과 등 환경 요인을 강하게 반영한다. 타고난 능력이나 집단의 우열을
// 나타내지 않으며, 페이지 상단의 경고 문구와 함께만 사용해야 한다.
// ESM 모듈 — wrangler가 worker.js로 번들.
export const COUNTRY_IQ = [
  { c: 'Japan', iq: 106 },
  { c: 'Taiwan', iq: 106 },
  { c: 'Singapore', iq: 106 },
  { c: 'South Korea', iq: 105 },
  { c: 'China', iq: 104 },
  { c: 'Hong Kong', iq: 105 },
  { c: 'Switzerland', iq: 102 },
  { c: 'Netherlands', iq: 102 },
  { c: 'Finland', iq: 101 },
  { c: 'Germany', iq: 101 },
  { c: 'Austria', iq: 101 },
  { c: 'Sweden', iq: 101 },
  { c: 'Italy', iq: 100 },
  { c: 'Belgium', iq: 100 },
  { c: 'Norway', iq: 100 },
  { c: 'United Kingdom', iq: 100 },
  { c: 'Denmark', iq: 100 },
  { c: 'Canada', iq: 100 },
  { c: 'New Zealand', iq: 100 },
  { c: 'Australia', iq: 99 },
  { c: 'France', iq: 99 },
  { c: 'United States', iq: 98 },
  { c: 'Spain', iq: 98 },
  { c: 'Russia', iq: 97 },
  { c: 'Poland', iq: 99 },
  { c: 'Ireland', iq: 98 },
  { c: 'Portugal', iq: 96 },
  { c: 'Hungary', iq: 98 },
  { c: 'Czechia', iq: 99 },
  { c: 'Greece', iq: 95 },
  { c: 'Vietnam', iq: 94 },
  { c: 'Argentina', iq: 93 },
  { c: 'Turkey', iq: 90 },
  { c: 'Mexico', iq: 88 },
  { c: 'Brazil', iq: 87 },
  { c: 'Thailand', iq: 89 },
  { c: 'Indonesia', iq: 87 },
  { c: 'Iran', iq: 84 },
  { c: 'India', iq: 82 },
  { c: 'Egypt', iq: 83 },
  { c: 'Philippines', iq: 86 },
  { c: 'South Africa', iq: 77 },
  { c: 'Nigeria', iq: 78 },
  { c: 'Kenya', iq: 74 },
];
