name = "iq-test-webapp"
main = "worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "all-lifes.com/iq-test*", zone_name = "all-lifes.com" }
]

[assets]
directory = "."
binding = "ASSETS"
